version: 2
updates:
  - package-ecosystem: "pip" # See documentation for possible values
    directory: "/" # Location of package manifests
    versioning-strategy: lockfile-only
    schedule:
      interval: weekly
      day: saturday
      time: "16:00"
  - package-ecosystem: "github-actions"
    directory: "/"
