name: Run Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.rst'
  push:
    branches:
      - master
      - ci/*
    paths-ignore:
      - '**.md'
      - '**.rst'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]
        poetry-version: [1.1.4]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.1.2
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Get poetry cache dir
        id: poetry-cache
        run: |
          echo "::set-output name=dir::$(poetry config cache-dir)"
      - name: Cache Poetry
        uses: actions/cache@v2.1.6
        id: cache
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key: poetry-cache-v1-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.poetry-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-cache-v1-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.poetry-version }}
            poetry-cache-v1-${{ matrix.os }}-${{ matrix.python-version }}
            poetry-cache-v1-${{ matrix.os }}
      - name: Check Venv And Install Requirements
        shell: bash
        run: |
          poetry run python -c 'import pytest' || \
          ( poetry install --no-root && poetry run python -c 'import pytest' ) || \
          ( poetry env remove python && poetry install --no-root && poetry run python -c 'import pytest' )
      - name: Run Tests
        if: "! (matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8')"
        run: poetry run pytest
      - name: Run Tests with Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
        run: |
          poetry run pytest --cov --cov-report=xml
      - name: Upload coverage to Codecov
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
        uses: codecov/codecov-action@v2.0.2
