name: Run Tests

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches: [master]
    paths-ignore:
      - '**.md'

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.6, 3.7, 3.8]
        poetry-version: [1.1.2]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Get poetry cache dir
        id: poetry-cache
        run: |
          echo "::set-output name=dir::$(poetry config cache-dir)"
      - name: Cache Poetry
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ steps.poetry-cache.outputs.dir }}
          key: ${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.poetry-version }}-${{ hashFiles('poetry.lock') }}
          restore-keys: |
            poetry-cache-v1-
      - name: Install Requirements
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install --no-root
      - name: Run Tests
        if: "! (matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8')"
        run: poetry run pytest
      - name: Run Tests with Coverage
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
        run: |
          poetry run pytest --cov --cov-report=xml
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.8'
        with:
          name: coverage.xml
          path: coverage.xml
